import mongoose from "mongoose";
import dotenv from "dotenv";
import { obtenerModeloFiguritas } from "../models/modeloFigu.js";

dotenv.config();

await mongoose.connect(process.env.MONGO_URL);



const Figurita = obtenerModeloFiguritas("mundialUsa2026");

const figuritas = await Figurita.find();

const nombres = [
    {NUM:"ALG1",NOMBRE:"Foto del escudo"},
{NUM:"ALG2",NOMBRE:"Alexis Guendouz"},
{NUM:"ALG3",NOMBRE:"Ramy Bensebaini"},
{NUM:"ALG4",NOMBRE:"Youcef Atal"},
{NUM:"ALG5",NOMBRE:"Rayan Aït-Nouri"},
{NUM:"ALG6",NOMBRE:"Mohamed Amine Tougai"},
{NUM:"ALG7",NOMBRE:"Aïssa Mandi"},
{NUM:"ALG8",NOMBRE:"Ismael Bennacer"},
{NUM:"ALG9",NOMBRE:"Houssem Aquar"},
{NUM:"ALG10",NOMBRE:"Hicham Boudaoui"},
{NUM:"ALG11",NOMBRE:"Ramiz Zerrouki"},
{NUM:"ALG12",NOMBRE:"Nabil Bentalab"},
{NUM:"ALG13",NOMBRE:"Foto del equipo"},
{NUM:"ALG14",NOMBRE:"Farés Chaibi"},
{NUM:"ALG15",NOMBRE:"Riyad Mahrez"},
{NUM:"ALG16",NOMBRE:"Said Benrahma"},
{NUM:"ALG17",NOMBRE:"Anis Hadj Moussa"},
{NUM:"ALG18",NOMBRE:"Amine Gouiri"},
{NUM:"ALG19",NOMBRE:"Baghdad Bounedjah"},
{NUM:"ALG20",NOMBRE:"Mohammed Amoura"},
{NUM:"ARG1",NOMBRE:"Foto del escudo"},
{NUM:"ARG2",NOMBRE:"Emiliano Martinez"},
{NUM:"ARG3",NOMBRE:"Nahuel Molina"},
{NUM:"ARG4",NOMBRE:"Cristian Romero"},
{NUM:"ARG5",NOMBRE:"Nicolas Otamendi"},
{NUM:"ARG6",NOMBRE:"Nicolas Tagliafico"},
{NUM:"ARG7",NOMBRE:"Leonardo Balerdi"},
{NUM:"ARG8",NOMBRE:"Enzo Fernandez"},
{NUM:"ARG9",NOMBRE:"Alexis Mac Allister"},
{NUM:"ARG10",NOMBRE:"Rodrigo De Paul"},
{NUM:"ARG11",NOMBRE:"Exequiel Palacios"},
{NUM:"ARG12",NOMBRE:"Leandro Paredes"},
{NUM:"ARG13",NOMBRE:"Foto del equipo"},
{NUM:"ARG14",NOMBRE:"Nico Paz"},
{NUM:"ARG15",NOMBRE:"Franco Mastantuono"},
{NUM:"ARG16",NOMBRE:"Nico Gonzalez"},
{NUM:"ARG17",NOMBRE:"Lionel Messi"},
{NUM:"ARG18",NOMBRE:"Lautaro Martinez"},
{NUM:"ARG19",NOMBRE:"Julian Alvarez"},
{NUM:"ARG20",NOMBRE:"Giuliano Simeone"},
{NUM:"AUS1",NOMBRE:"Foto del escudo"},
{NUM:"AUS2",NOMBRE:"Mathew Ryan"},
{NUM:"AUS3",NOMBRE:"Joe Gauci"},
{NUM:"AUS4",NOMBRE:"Harry Souttar"},
{NUM:"AUS5",NOMBRE:"Alessandro Circati"},
{NUM:"AUS6",NOMBRE:"Jordan Bos"},
{NUM:"AUS7",NOMBRE:"Aziz Behich"},
{NUM:"AUS8",NOMBRE:"Cameron Burgess"},
{NUM:"AUS9",NOMBRE:"Lewis Miller"},
{NUM:"AUS10",NOMBRE:"Milos Degenek"},
{NUM:"AUS11",NOMBRE:"Jackson Irvine"},
{NUM:"AUS12",NOMBRE:"Riley McGree"},
{NUM:"AUS13",NOMBRE:"Foto del equipo"},
{NUM:"AUS14",NOMBRE:"Aiden O'Neill"},
{NUM:"AUS15",NOMBRE:"Connor Metcalfe"},
{NUM:"AUS16",NOMBRE:"Patrick Yazbek"},
{NUM:"AUS17",NOMBRE:"Craig Goodwin"},
{NUM:"AUS18",NOMBRE:"Kusini Vengi"},
{NUM:"AUS19",NOMBRE:"Nestory Irankunda"},
{NUM:"AUS20",NOMBRE:"Mohamed Touré"},
{NUM:"AUT1",NOMBRE:"Foto del escudo"},
{NUM:"AUT2",NOMBRE:"Alexander Schlager"},
{NUM:"AUT3",NOMBRE:"Patrick Pentz"},
{NUM:"AUT4",NOMBRE:"David Alaba"},
{NUM:"AUT5",NOMBRE:"Kevin Danso"},
{NUM:"AUT6",NOMBRE:"Philipp Lienhart"},
{NUM:"AUT7",NOMBRE:"Stefan Posch"},
{NUM:"AUT8",NOMBRE:"Phillipp Mwene"},
{NUM:"AUT9",NOMBRE:"Alexander Prass"},
{NUM:"AUT10",NOMBRE:"Xaver Schlager"},
{NUM:"AUT11",NOMBRE:"Marcel Sabitzer"},
{NUM:"AUT12",NOMBRE:"Konrad Laimer"},
{NUM:"AUT13",NOMBRE:"Foto del equipo"},
{NUM:"AUT14",NOMBRE:"Florian Grillitsch"},
{NUM:"AUT15",NOMBRE:"Nicolas Seiwald"},
{NUM:"AUT16",NOMBRE:"Romano Schmid"},
{NUM:"AUT17",NOMBRE:"Patrick Wimmer"},
{NUM:"AUT18",NOMBRE:"Christoph Baumgartner"},
{NUM:"AUT19",NOMBRE:"Michael Gregoritsch"},
{NUM:"AUT20",NOMBRE:"Marko Arnautović"},
{NUM:"BEL1",NOMBRE:"Foto del escudo"},
{NUM:"BEL2",NOMBRE:"Thibaut Courtois"},
{NUM:"BEL3",NOMBRE:"Arthur Theate"},
{NUM:"BEL4",NOMBRE:"Timothy Castagne"},
{NUM:"BEL5",NOMBRE:"Zeno Debast"},
{NUM:"BEL6",NOMBRE:"Brandon Mechele"},
{NUM:"BEL7",NOMBRE:"Maxim De Cuyper"},
{NUM:"BEL8",NOMBRE:"Thomas Meunier"},
{NUM:"BEL9",NOMBRE:"Youri Tielemans"},
{NUM:"BEL10",NOMBRE:"Amadou Onana"},
{NUM:"BEL11",NOMBRE:"Nicolas Raskin"},
{NUM:"BEL12",NOMBRE:"Alexis Saelemaekers"},
{NUM:"BEL13",NOMBRE:"Foto del equipo"},
{NUM:"BEL14",NOMBRE:"Hans Vanaken"},
{NUM:"BEL15",NOMBRE:"Kevin De Bruyne"},
{NUM:"BEL16",NOMBRE:"Jérémy Doku"},
{NUM:"BEL17",NOMBRE:"Charles De Ketelaere"},
{NUM:"BEL18",NOMBRE:"Leandro Trossard"},
{NUM:"BEL19",NOMBRE:"Loïs Openda"},
{NUM:"BEL20",NOMBRE:"Romelu Lukaku"},
{NUM:"BIH1",NOMBRE:"Foto del escudo"},
{NUM:"BIH2",NOMBRE:"Nikola Vasilj"},
{NUM:"BIH3",NOMBRE:"Amer Dedic"},
{NUM:"BIH4",NOMBRE:"Sead Kolasinac"},
{NUM:"BIH5",NOMBRE:"Tarik Muharemovic"},
{NUM:"BIH6",NOMBRE:"Nihad Mujakic"},
{NUM:"BIH7",NOMBRE:"Nikola Katic"},
{NUM:"BIH8",NOMBRE:"Amir Hadziahmetovic"},
{NUM:"BIH9",NOMBRE:"Benjamin Tahirovic"},
{NUM:"BIH10",NOMBRE:"Armin Gigovic"},
{NUM:"BIH11",NOMBRE:"Ivan Sunjic"},
{NUM:"BIH12",NOMBRE:"Ivan Basic"},
{NUM:"BIH13",NOMBRE:"Foto del equipo"},
{NUM:"BIH14",NOMBRE:"Dzenis Burnic"},
{NUM:"BIH15",NOMBRE:"Esmir Bajraktarevic"},
{NUM:"BIH16",NOMBRE:"Amar Memic"},
{NUM:"BIH17",NOMBRE:"Ermedin Demirovic"},
{NUM:"BIH18",NOMBRE:"Edin Dzeko"},
{NUM:"BIH19",NOMBRE:"Samed Bazdar"},
{NUM:"BIH20",NOMBRE:"Haris Tabakovic"},
{NUM:"BRA1",NOMBRE:"Foto del escudo"},
{NUM:"BRA2",NOMBRE:"Alisson"},
{NUM:"BRA3",NOMBRE:"Bento"},
{NUM:"BRA4",NOMBRE:"Marquinhos"},
{NUM:"BRA5",NOMBRE:"Éder Militão"},
{NUM:"BRA6",NOMBRE:"Gabriel Magalhães"},
{NUM:"BRA7",NOMBRE:"Danilo"},
{NUM:"BRA8",NOMBRE:"Wesley"},
{NUM:"BRA9",NOMBRE:"Lucas Paquetá"},
{NUM:"BRA10",NOMBRE:"Casemiro"},
{NUM:"BRA11",NOMBRE:"Bruno Guimarães"},
{NUM:"BRA12",NOMBRE:"Luiz Henrique"},
{NUM:"BRA13",NOMBRE:"Foto del equipo"},
{NUM:"BRA14",NOMBRE:"Vinicius Júnior"},
{NUM:"BRA15",NOMBRE:"Rodrygo"},
{NUM:"BRA16",NOMBRE:"João Pedro"},
{NUM:"BRA17",NOMBRE:"Matheus Cunha"},
{NUM:"BRA18",NOMBRE:"Gabriel Martinelli"},
{NUM:"BRA19",NOMBRE:"Raphinha"},
{NUM:"BRA20",NOMBRE:"Estévão"},
{NUM:"CAN1",NOMBRE:"Foto del escudo"},
{NUM:"CAN2",NOMBRE:"Dayne St.Clair"},
{NUM:"CAN3",NOMBRE:"Alphonso Davies"},
{NUM:"CAN4",NOMBRE:"Alistair Johnston"},
{NUM:"CAN5",NOMBRE:"Samuel Adekugbe"},
{NUM:"CAN6",NOMBRE:"Riche Larvea"},
{NUM:"CAN7",NOMBRE:"Derek Cornelius"},
{NUM:"CAN8",NOMBRE:"Moïse Bombito"},
{NUM:"CAN9",NOMBRE:"Kamal Miller"},
{NUM:"CAN10",NOMBRE:"Stephen Eustáquio"},
{NUM:"CAN11",NOMBRE:"Ismaël Koné"},
{NUM:"CAN12",NOMBRE:"Jonathan Osorio"},
{NUM:"CAN13",NOMBRE:"Foto del equipo"},
{NUM:"CAN14",NOMBRE:"Jacob Shaffelburg"},
{NUM:"CAN15",NOMBRE:"Mathieu Choinière"},
{NUM:"CAN16",NOMBRE:"Niko Sigur"},
{NUM:"CAN17",NOMBRE:"Tajon Buchanan"},
{NUM:"CAN18",NOMBRE:"Liam Millar"},
{NUM:"CAN19",NOMBRE:"Cyle Larin"},
{NUM:"CAN20",NOMBRE:"Jonathan David"},
{NUM:"CIV1",NOMBRE:"Foto del escudo"},
{NUM:"CIV2",NOMBRE:"Yahia Fofana"},
{NUM:"CIV3",NOMBRE:"Ghislain Konan"},
{NUM:"CIV4",NOMBRE:"Wilfried Singo"},
{NUM:"CIV5",NOMBRE:"Odilon Kossounou"},
{NUM:"CIV6",NOMBRE:"Evan Ndicka"},
{NUM:"CIV7",NOMBRE:"Willy Boly"},
{NUM:"CIV8",NOMBRE:"Emmanuel Agbadou"},
{NUM:"CIV9",NOMBRE:"Ousmane Diomande"},
{NUM:"CIV10",NOMBRE:"Franck Kessie"},
{NUM:"CIV11",NOMBRE:"Seko Fofana"},
{NUM:"CIV12",NOMBRE:"Ibrahim Sangare"},
{NUM:"CIV13",NOMBRE:"Foto del equipo"},
{NUM:"CIV14",NOMBRE:"Jean-Philippe Gbamin"},
{NUM:"CIV15",NOMBRE:"Amad Diallo"},
{NUM:"CIV16",NOMBRE:"Sébastien Haller"},
{NUM:"CIV17",NOMBRE:"Simon Adingra"},
{NUM:"CIV18",NOMBRE:"Yan Diomande"},
{NUM:"CIV19",NOMBRE:"Evann Guessand"},
{NUM:"CIV20",NOMBRE:"Oumar Diakite"},
{NUM:"COD1",NOMBRE:"Foto del escudo"},
{NUM:"COD2",NOMBRE:"Lionel Mpasi"},
{NUM:"COD3",NOMBRE:"Aaron Wan-Bissaka"},
{NUM:"COD4",NOMBRE:"Axel Tuanzebe"},
{NUM:"COD5",NOMBRE:"Arthur Masuaku"},
{NUM:"COD6",NOMBRE:"Chancel Mbemba"},
{NUM:"COD7",NOMBRE:"Joris Kayembe"},
{NUM:"COD8",NOMBRE:"Charles Pickel"},
{NUM:"COD9",NOMBRE:"Ngal'ayel Mukau"},
{NUM:"COD10",NOMBRE:"Edo Kayembe"},
{NUM:"COD11",NOMBRE:"Samuel Moutoussamy"},
{NUM:"COD12",NOMBRE:"Noah Sadiki"},
{NUM:"COD13",NOMBRE:"Foto del equipo"},
{NUM:"COD14",NOMBRE:"Théo Bongonda"},
{NUM:"COD15",NOMBRE:"Meschak Elia"},
{NUM:"COD16",NOMBRE:"Yoane Wissa"},
{NUM:"COD17",NOMBRE:"Brian Cipenga"},
{NUM:"COD18",NOMBRE:"Fiston Mayele"},
{NUM:"COD19",NOMBRE:"Cédric Bakambu"},
{NUM:"COD20",NOMBRE:"Nathanaël Mbuku"},
{NUM:"COL1",NOMBRE:"Foto del escudo"},
{NUM:"COL2",NOMBRE:"Camilo Vargas"},
{NUM:"COL3",NOMBRE:"David Ospina"},
{NUM:"COL4",NOMBRE:"Dávinson Sánchez"},
{NUM:"COL5",NOMBRE:"Yerry Mina"},
{NUM:"COL6",NOMBRE:"Daniel Munoz"},
{NUM:"COL7",NOMBRE:"Johan Mojica"},
{NUM:"COL8",NOMBRE:"Jhon Lucumí"},
{NUM:"COL9",NOMBRE:"Santiago Arias"},
{NUM:"COL10",NOMBRE:"Jefferson Lerma"},
{NUM:"COL11",NOMBRE:"Kevin Castaño"},
{NUM:"COL12",NOMBRE:"Richard Rios"},
{NUM:"COL13",NOMBRE:"Foto del equipo"},
{NUM:"COL14",NOMBRE:"James Rodriguez"},
{NUM:"COL15",NOMBRE:"Juan Fernando Quintero"},
{NUM:"COL16",NOMBRE:"Jorge Carrascal"},
{NUM:"COL17",NOMBRE:"Jon Arias"},
{NUM:"COL18",NOMBRE:"Jhon Cordova"},
{NUM:"COL19",NOMBRE:"Luis Suarez"},
{NUM:"COL20",NOMBRE:"Luis Diaz"},
{NUM:"CPV1",NOMBRE:"Foto del escudo"},
{NUM:"CPV2",NOMBRE:"Vozinha"},
{NUM:"CPV3",NOMBRE:"Logan Costa"},
{NUM:"CPV4",NOMBRE:"Pico"},
{NUM:"CPV5",NOMBRE:"Diney"},
{NUM:"CPV6",NOMBRE:"Steven Moreira"},
{NUM:"CPV7",NOMBRE:"Wagner Pina"},
{NUM:"CPV8",NOMBRE:"Joao Paulo"},
{NUM:"CPV9",NOMBRE:"Yannick Semedo"},
{NUM:"CPV10",NOMBRE:"Kevin Pina"},
{NUM:"CPV11",NOMBRE:"Patrick Andrade"},
{NUM:"CPV12",NOMBRE:"Jamiro Monteiro"},
{NUM:"CPV13",NOMBRE:"Foto del equipo"},
{NUM:"CPV14",NOMBRE:"Deroy Duarte"},
{NUM:"CPV15",NOMBRE:"Garry Rodrigues"},
{NUM:"CPV16",NOMBRE:"Jovane Cabral"},
{NUM:"CPV17",NOMBRE:"Ryan Mendes"},
{NUM:"CPV18",NOMBRE:"Dailon Livramento"},
{NUM:"CPV19",NOMBRE:"Willy Semedo"},
{NUM:"CPV20",NOMBRE:"Bebe"},
{NUM:"CRO1",NOMBRE:"Foto del escudo"},
{NUM:"CRO2",NOMBRE:"Dominik Livaković"},
{NUM:"CRO3",NOMBRE:"Duje Caleta-Car"},
{NUM:"CRO4",NOMBRE:"Josko Gvardiol"},
{NUM:"CRO5",NOMBRE:"Josip Stanišić"},
{NUM:"CRO6",NOMBRE:"Luka Vušković"},
{NUM:"CRO7",NOMBRE:"Josip Sutalo"},
{NUM:"CRO8",NOMBRE:"Kristijan Jakic"},
{NUM:"CRO9",NOMBRE:"Luka Modrić"},
{NUM:"CRO10",NOMBRE:"Mateo Kovacic"},
{NUM:"CRO11",NOMBRE:"Martin Baturina"},
{NUM:"CRO12",NOMBRE:"Lovro Majer"},
{NUM:"CRO13",NOMBRE:"Foto del equipo"},
{NUM:"CRO14",NOMBRE:"Mario Pasalic"},
{NUM:"CRO15",NOMBRE:"Petar Sucic"},
{NUM:"CRO16",NOMBRE:"Ivan Perišić"},
{NUM:"CRO17",NOMBRE:"Marco Pasalic"},
{NUM:"CRO18",NOMBRE:"Ante Budimir"},
{NUM:"CRO19",NOMBRE:"Andrej Kramarić"},
{NUM:"CRO20",NOMBRE:"Franjo Ivanovic"},
{NUM:"CUW1",NOMBRE:"Foto del escudo"},
{NUM:"CUW2",NOMBRE:"Eloy Room"},
{NUM:"CUW3",NOMBRE:"Armando Obispo"},
{NUM:"CUW4",NOMBRE:"Sherel Floranus"},
{NUM:"CUW5",NOMBRE:"Jurien Gaari"},
{NUM:"CUW6",NOMBRE:"Joshua Brenet"},
{NUM:"CUW7",NOMBRE:"Roshon Van Eijma"},
{NUM:"CUW8",NOMBRE:"Shurandy Sambo"},
{NUM:"CUW9",NOMBRE:"Livano Comenencia"},
{NUM:"CUW10",NOMBRE:"Godfried Roemeratoe"},
{NUM:"CUW11",NOMBRE:"Juninho Bacuna"},
{NUM:"CUW12",NOMBRE:"Leandro Bacuna"},
{NUM:"CUW13",NOMBRE:"Foto del equipo"},
{NUM:"CUW14",NOMBRE:"Tahith Chong"},
{NUM:"CUW15",NOMBRE:"Kenji Gorre"},
{NUM:"CUW16",NOMBRE:"Jearl Margaritha"},
{NUM:"CUW17",NOMBRE:"Jurgen Locadia"},
{NUM:"CUW18",NOMBRE:"Jeremy Antonisse"},
{NUM:"CUW19",NOMBRE:"Gervane Kastaneer"},
{NUM:"CUW20",NOMBRE:"Sontje Hansen"},
{NUM:"CZE1",NOMBRE:"Foto del escudo"},
{NUM:"CZE2",NOMBRE:"Matej Kovar"},
{NUM:"CZE3",NOMBRE:"Jindrich Stanek"},
{NUM:"CZE4",NOMBRE:"Ladislav Krejci"},
{NUM:"CZE5",NOMBRE:"Vladimir Coufal"},
{NUM:"CZE6",NOMBRE:"Jaroslav Zeleny"},
{NUM:"CZE7",NOMBRE:"Tomas Holes"},
{NUM:"CZE8",NOMBRE:"David Zima"},
{NUM:"CZE9",NOMBRE:"Michal Sadilek"},
{NUM:"CZE10",NOMBRE:"Lukas Provod"},
{NUM:"CZE11",NOMBRE:"Lukas Cerv"},
{NUM:"CZE12",NOMBRE:"Tomas Soucek"},
{NUM:"CZE13",NOMBRE:"Foto del equipo"},
{NUM:"CZE14",NOMBRE:"Pavel Sulc"},
{NUM:"CZE15",NOMBRE:"Matej Vydra"},
{NUM:"CZE16",NOMBRE:"Vasil Kusej"},
{NUM:"CZE17",NOMBRE:"Tomas Chory"},
{NUM:"CZE18",NOMBRE:"Vaclav Cerny"},
{NUM:"CZE19",NOMBRE:"Adam Hlozek"},
{NUM:"CZE20",NOMBRE:"Patrik Schick"},
{NUM:"ECU1",NOMBRE:"Foto del escudo"},
{NUM:"ECU2",NOMBRE:"Hernán Galíndez"},
{NUM:"ECU3",NOMBRE:"Gonzalo Valle"},
{NUM:"ECU4",NOMBRE:"Piero Hincapié"},
{NUM:"ECU5",NOMBRE:"Pervis Estupiñán"},
{NUM:"ECU6",NOMBRE:"Willian Pacho"},
{NUM:"ECU7",NOMBRE:"Ángelo Preciado"},
{NUM:"ECU8",NOMBRE:"Joel Ordóñez"},
{NUM:"ECU9",NOMBRE:"Moises Caicedo"},
{NUM:"ECU10",NOMBRE:"Alan Franco"},
{NUM:"ECU11",NOMBRE:"Kendry Paez"},
{NUM:"ECU12",NOMBRE:"Pedro Vite"},
{NUM:"ECU13",NOMBRE:"Foto del equipo"},
{NUM:"ECU14",NOMBRE:"John Veboah"},
{NUM:"ECU15",NOMBRE:"Leonardo Campana"},
{NUM:"ECU16",NOMBRE:"Gonzalo Plata"},
{NUM:"ECU17",NOMBRE:"Nilson Angulo"},
{NUM:"ECU18",NOMBRE:"Alan Minda"},
{NUM:"ECU19",NOMBRE:"Kevin Rodriguez"},
{NUM:"ECU20",NOMBRE:"Enner Valencia"},
{NUM:"EGY1",NOMBRE:"Foto del escudo"},
{NUM:"EGY2",NOMBRE:"Mohamed El Shenawy"},
{NUM:"EGY3",NOMBRE:"Mohamed Hany"},
{NUM:"EGY4",NOMBRE:"Mohamed Hamdy"},
{NUM:"EGY5",NOMBRE:"Yasser Ibrahim"},
{NUM:"EGY6",NOMBRE:"Khaled Sobhi"},
{NUM:"EGY7",NOMBRE:"Ramy Rabia"},
{NUM:"EGY8",NOMBRE:"Hossam Abdelmaguid"},
{NUM:"EGY9",NOMBRE:"Ahmed Fatouh"},
{NUM:"EGY10",NOMBRE:"Marwan Attia"},
{NUM:"EGY11",NOMBRE:"Zizo"},
{NUM:"EGY12",NOMBRE:"Hamdy Fathy"},
{NUM:"EGY13",NOMBRE:"Foto del equipo"},
{NUM:"EGY14",NOMBRE:"Mohamed Lasheen"},
{NUM:"EGY15",NOMBRE:"Emam Ashour"},
{NUM:"EGY16",NOMBRE:"Osama Faisal"},
{NUM:"EGY17",NOMBRE:"Mohamed Salah"},
{NUM:"EGY18",NOMBRE:"Mostafa Mohamed"},
{NUM:"EGY19",NOMBRE:"Trezeguet"},
{NUM:"EGY20",NOMBRE:"Omar Marmoush"},
{NUM:"ENG1",NOMBRE:"Foto del escudo"},
{NUM:"ENG2",NOMBRE:"Jordan Pickford"},
{NUM:"ENG3",NOMBRE:"John Stones"},
{NUM:"ENG4",NOMBRE:"Marc Guéhi"},
{NUM:"ENG5",NOMBRE:"Ezri Konsa"},
{NUM:"ENG6",NOMBRE:"Trent Alexander-Arnold"},
{NUM:"ENG7",NOMBRE:"Reece James"},
{NUM:"ENG8",NOMBRE:"Dan Burn"},
{NUM:"ENG9",NOMBRE:"Jordan Henderson"},
{NUM:"ENG10",NOMBRE:"Declan Rice"},
{NUM:"ENG11",NOMBRE:"Jude Bellingham"},
{NUM:"ENG12",NOMBRE:"Cole Palmer"},
{NUM:"ENG13",NOMBRE:"Foto del equipo"},
{NUM:"ENG14",NOMBRE:"Morgan Rogers"},
{NUM:"ENG15",NOMBRE:"Anthony Gordon"},
{NUM:"ENG16",NOMBRE:"Phil Foden"},
{NUM:"ENG17",NOMBRE:"Bukayo Saka"},
{NUM:"ENG18",NOMBRE:"Harry Kane"},
{NUM:"ENG19",NOMBRE:"Marcus Rashford"},
{NUM:"ENG20",NOMBRE:"Ollie Watkins"},
{NUM:"ESP1",NOMBRE:"Foto del escudo"},
{NUM:"ESP2",NOMBRE:"Unai Simon"},
{NUM:"ESP3",NOMBRE:"Robin Le Normand"},
{NUM:"ESP4",NOMBRE:"Aymeric Laporte"},
{NUM:"ESP5",NOMBRE:"Dean Huijsen"},
{NUM:"ESP6",NOMBRE:"Pedro Porro"},
{NUM:"ESP7",NOMBRE:"Dani Carvajal"},
{NUM:"ESP8",NOMBRE:"Marc Cucurella"},
{NUM:"ESP9",NOMBRE:"Martín Zubimendi"},
{NUM:"ESP10",NOMBRE:"Rodri"},
{NUM:"ESP11",NOMBRE:"Pedri"},
{NUM:"ESP12",NOMBRE:"Fabian Ruiz"},
{NUM:"ESP13",NOMBRE:"Foto del equipo"},
{NUM:"ESP14",NOMBRE:"Mikel Merino"},
{NUM:"ESP15",NOMBRE:"Lamine Yamal"},
{NUM:"ESP16",NOMBRE:"Dani Olmo"},
{NUM:"ESP17",NOMBRE:"Nico Williams"},
{NUM:"ESP18",NOMBRE:"Ferran Torres"},
{NUM:"ESP19",NOMBRE:"Álvaro Morata"},
{NUM:"ESP20",NOMBRE:"Mikel Oyarzabal"},
{NUM:"FRA1",NOMBRE:"Foto del escudo"},
{NUM:"FRA2",NOMBRE:"Mike Maignan"},
{NUM:"FRA3",NOMBRE:"Theo Hernandez"},
{NUM:"FRA4",NOMBRE:"William Saliba"},
{NUM:"FRA5",NOMBRE:"Jules Kounde"},
{NUM:"FRA6",NOMBRE:"Ibrahima Konate"},
{NUM:"FRA7",NOMBRE:"Dayot Upamecano"},
{NUM:"FRA8",NOMBRE:"Lucas Digne"},
{NUM:"FRA9",NOMBRE:"Aurélien Tchouaméni"},
{NUM:"FRA10",NOMBRE:"Eduardo Camavinga"},
{NUM:"FRA11",NOMBRE:"Manu Kone"},
{NUM:"FRA12",NOMBRE:"Adrien Rabiot"},
{NUM:"FRA13",NOMBRE:"Foto del equipo"},
{NUM:"FRA14",NOMBRE:"Michael Olise"},
{NUM:"FRA15",NOMBRE:"Ousmane Dembele"},
{NUM:"FRA16",NOMBRE:"Bradley Barcola"},
{NUM:"FRA17",NOMBRE:"Désiré Doué"},
{NUM:"FRA18",NOMBRE:"Kingsley Coman"},
{NUM:"FRA19",NOMBRE:"Hugo Ekitike"},
{NUM:"FRA20",NOMBRE:"Kylian Mbappe"},
{NUM:"GER1",NOMBRE:"Foto del escudo"},
{NUM:"GER2",NOMBRE:"Marc-André ter Stegen"},
{NUM:"GER3",NOMBRE:"Jonathan Tah"},
{NUM:"GER4",NOMBRE:"David Raum"},
{NUM:"GER5",NOMBRE:"Nico Schlotterbeck"},
{NUM:"GER6",NOMBRE:"Antonio Rüdiger"},
{NUM:"GER7",NOMBRE:"Waldemar Anton"},
{NUM:"GER8",NOMBRE:"Ridle Baku"},
{NUM:"GER9",NOMBRE:"Maximilian Mittelstadt"},
{NUM:"GER10",NOMBRE:"Joshua Kimmich"},
{NUM:"GER11",NOMBRE:"Florian Wirtz"},
{NUM:"GER12",NOMBRE:"Felix Nmecha"},
{NUM:"GER13",NOMBRE:"Foto del equipo"},
{NUM:"GER14",NOMBRE:"Leon Goretzka"},
{NUM:"GER15",NOMBRE:"Jamal Musiala"},
{NUM:"GER16",NOMBRE:"Serge Gnabry"},
{NUM:"GER17",NOMBRE:"Kai Havertz"},
{NUM:"GER18",NOMBRE:"Leroy Sane"},
{NUM:"GER19",NOMBRE:"Karim Adeyemi"},
{NUM:"GER20",NOMBRE:"Nick Woltemade"},
{NUM:"GHA1",NOMBRE:"Foto del escudo"},
{NUM:"GHA2",NOMBRE:"Lawrence Ati Zigi"},
{NUM:"GHA3",NOMBRE:"Tariq Lamptey"},
{NUM:"GHA4",NOMBRE:"Mohammed Salisu"},
{NUM:"GHA5",NOMBRE:"Alidu Seidu"},
{NUM:"GHA6",NOMBRE:"Alexander Djiku"},
{NUM:"GHA7",NOMBRE:"Gideon Mensah"},
{NUM:"GHA8",NOMBRE:"Caleb Yirenkyi"},
{NUM:"GHA9",NOMBRE:"Abdul Issahaku Fatawu"},
{NUM:"GHA10",NOMBRE:"Thomas Partey"},
{NUM:"GHA11",NOMBRE:"Salis Abdul Samed"},
{NUM:"GHA12",NOMBRE:"Kamaldeen Sulemana"},
{NUM:"GHA13",NOMBRE:"Foto del equipo"},
{NUM:"GHA14",NOMBRE:"Mohammed Kudus"},
{NUM:"GHA15",NOMBRE:"Inaki Williams"},
{NUM:"GHA16",NOMBRE:"Jordan Ayew"},
{NUM:"GHA17",NOMBRE:"Andrew Ayew"},
{NUM:"GHA18",NOMBRE:"Joseph Paintsil"},
{NUM:"GHA19",NOMBRE:"Osman Bukari"},
{NUM:"GHA20",NOMBRE:"Antoine Semenyo"},
{NUM:"HAI1",NOMBRE:"Foto del escudo"},
{NUM:"HAI2",NOMBRE:"Johny Placide"},
{NUM:"HAI3",NOMBRE:"Carlens Arcus"},
{NUM:"HAI4",NOMBRE:"Martin Expérience"},
{NUM:"HAI5",NOMBRE:"Jean-Kevin Duverne"},
{NUM:"HAI6",NOMBRE:"Ricardo Adé"},
{NUM:"HAI7",NOMBRE:"Duke Lacroix"},
{NUM:"HAI8",NOMBRE:"Garven Metusala"},
{NUM:"HAI9",NOMBRE:"Hannes Delcroix"},
{NUM:"HAI10",NOMBRE:"Leverton Pierre"},
{NUM:"HAI11",NOMBRE:"Danley Jean Jacques"},
{NUM:"HAI12",NOMBRE:"Jean-Ricner Bellegarde"},
{NUM:"HAI13",NOMBRE:"Foto del equipo"},
{NUM:"HAI14",NOMBRE:"Christopher Attys"},
{NUM:"HAI15",NOMBRE:"Derrick Etienne Jr"},
{NUM:"HAI16",NOMBRE:"Josue Casimir"},
{NUM:"HAI17",NOMBRE:"Ruben Providence"},
{NUM:"HAI18",NOMBRE:"Duckens Nazon"},
{NUM:"HAI19",NOMBRE:"Louicius Deedson"},
{NUM:"HAI20",NOMBRE:"Frantzdy Pierrot"},
{NUM:"IRN1",NOMBRE:"Foto del escudo"},
{NUM:"IRN2",NOMBRE:"Alireza Beiranvand"},
{NUM:"IRN3",NOMBRE:"Morteza Pouraliganji"},
{NUM:"IRN4",NOMBRE:"Ehsan Hajsafi"},
{NUM:"IRN5",NOMBRE:"Milad Mohammadi"},
{NUM:"IRN6",NOMBRE:"Shojae Khalilzadeh"},
{NUM:"IRN7",NOMBRE:"Ramin Rezaeian"},
{NUM:"IRN8",NOMBRE:"Hossein Kanaani"},
{NUM:"IRN9",NOMBRE:"Sadegh Moharrami"},
{NUM:"IRN10",NOMBRE:"Saleh Hardani"},
{NUM:"IRN11",NOMBRE:"Saeed Ezatolahi"},
{NUM:"IRN12",NOMBRE:"Saman Ghoddos"},
{NUM:"IRN13",NOMBRE:"Foto del equipo"},
{NUM:"IRN14",NOMBRE:"Omid Noorafkan"},
{NUM:"IRN15",NOMBRE:"Roozbeh Cheshmi"},
{NUM:"IRN16",NOMBRE:"Mohammad Mohebi"},
{NUM:"IRN17",NOMBRE:"Sardar Azmoun"},
{NUM:"IRN18",NOMBRE:"Mehdi Taremi"},
{NUM:"IRN19",NOMBRE:"Alireza Jahanbakhsh"},
{NUM:"IRN20",NOMBRE:"Ali Gholizadeh"},
{NUM:"IRQ1",NOMBRE:"Foto del escudo"},
{NUM:"IRQ2",NOMBRE:"Jalal Hassan"},
{NUM:"IRQ3",NOMBRE:"Rebin Sulaka"},
{NUM:"IRQ4",NOMBRE:"Hussein Ali"},
{NUM:"IRQ5",NOMBRE:"Akam Hashem"},
{NUM:"IRQ6",NOMBRE:"Merchas Doski"},
{NUM:"IRQ7",NOMBRE:"Zaid Tahseen"},
{NUM:"IRQ8",NOMBRE:"Manaf Younis"},
{NUM:"IRQ9",NOMBRE:"Zidane Iqbal"},
{NUM:"IRQ10",NOMBRE:"Amir Al-Ammari"},
{NUM:"IRQ11",NOMBRE:"Ibrahim Bavesh"},
{NUM:"IRQ12",NOMBRE:"Ali Jasim"},
{NUM:"IRQ13",NOMBRE:"Foto del equipo"},
{NUM:"IRQ14",NOMBRE:"Youssef Amyn"},
{NUM:"IRQ15",NOMBRE:"Aimar Sher"},
{NUM:"IRQ16",NOMBRE:"Marko Farji"},
{NUM:"IRQ17",NOMBRE:"Osama Rashid"},
{NUM:"IRQ18",NOMBRE:"Ali Al-Hamadi"},
{NUM:"IRQ19",NOMBRE:"Aymen Hussein"},
{NUM:"IRQ20",NOMBRE:"Mohanad Ali"},
{NUM:"JOR1",NOMBRE:"Foto del escudo"},
{NUM:"JOR2",NOMBRE:"Yazeed Abulaila"},
{NUM:"JOR3",NOMBRE:"Ihsan Haddad"},
{NUM:"JOR4",NOMBRE:"Mohammad Abu Hashish"},
{NUM:"JOR5",NOMBRE:"Yazan Al-Arab"},
{NUM:"JOR6",NOMBRE:"Abdallah Nasib"},
{NUM:"JOR7",NOMBRE:"Saleem Obaid"},
{NUM:"JOR8",NOMBRE:"Mohammad Abualnadi"},
{NUM:"JOR9",NOMBRE:"Ibrahim Saadeh"},
{NUM:"JOR10",NOMBRE:"Nizar Al-Rashdan"},
{NUM:"JOR11",NOMBRE:"Noor Al-Rawabdeh"},
{NUM:"JOR12",NOMBRE:"Mohannad Abu Taha"},
{NUM:"JOR13",NOMBRE:"Foto del equipo"},
{NUM:"JOR14",NOMBRE:"Amer Jamous"},
{NUM:"JOR15",NOMBRE:"Musa Al-Taamari"},
{NUM:"JOR16",NOMBRE:"Yazan Al-Naimat"},
{NUM:"JOR17",NOMBRE:"Mahmoud Al-Mardi"},
{NUM:"JOR18",NOMBRE:"Ali Olwan"},
{NUM:"JOR19",NOMBRE:"Mohammad Abu Zrayq"},
{NUM:"JOR20",NOMBRE:"Ibrahim Sabra"},
{NUM:"JPN1",NOMBRE:"Foto del escudo"},
{NUM:"JPN2",NOMBRE:"Zion Suzuki"},
{NUM:"JPN3",NOMBRE:"Henry Heroki Mochizuki"},
{NUM:"JPN4",NOMBRE:"Ayumu Seko"},
{NUM:"JPN5",NOMBRE:"Junnosuke Suzuki"},
{NUM:"JPN6",NOMBRE:"Shogo Taniguchi"},
{NUM:"JPN7",NOMBRE:"Tsuyoshi Watanabe"},
{NUM:"JPN8",NOMBRE:"Kaishu Sano"},
{NUM:"JPN9",NOMBRE:"Yuki Soma"},
{NUM:"JPN10",NOMBRE:"Ao Tanaka"},
{NUM:"JPN11",NOMBRE:"Daichi Kamada"},
{NUM:"JPN12",NOMBRE:"Takefusa Kubo"},
{NUM:"JPN13",NOMBRE:"Foto del equipo"},
{NUM:"JPN14",NOMBRE:"Ritsu Doan"},
{NUM:"JPN15",NOMBRE:"Keito Nakamura"},
{NUM:"JPN16",NOMBRE:"Takumi Minamino"},
{NUM:"JPN17",NOMBRE:"Shuto Machino"},
{NUM:"JPN18",NOMBRE:"Junya Ito"},
{NUM:"JPN19",NOMBRE:"Koki Ogawa"},
{NUM:"JPN20",NOMBRE:"Ayase Ueda"},
{NUM:"KOR1",NOMBRE:"Foto del escudo"},
{NUM:"KOR2",NOMBRE:"Hyeon-woo Jo"},
{NUM:"KOR3",NOMBRE:"Seung-Gyu Kim"},
{NUM:"KOR4",NOMBRE:"Min-jae Kim"},
{NUM:"KOR5",NOMBRE:"Yu-min Cho"},
{NUM:"KOR6",NOMBRE:"Young-woo Seol"},
{NUM:"KOR7",NOMBRE:"Han-beom Lee"},
{NUM:"KOR8",NOMBRE:"Tae-seok Lee"},
{NUM:"KOR9",NOMBRE:"Myung-jae Lee"},
{NUM:"KOR10",NOMBRE:"Jae-sung Lee"},
{NUM:"KOR11",NOMBRE:"In-beom Hwang"},
{NUM:"KOR12",NOMBRE:"Kang-in Lee"},
{NUM:"KOR13",NOMBRE:"Foto del equipo"},
{NUM:"KOR14",NOMBRE:"Seung-ho Paik"},
{NUM:"KOR15",NOMBRE:"Jens Castrop"},
{NUM:"KOR16",NOMBRE:"Dongg-yeong Lee"},
{NUM:"KOR17",NOMBRE:"Gue-sung Cho"},
{NUM:"KOR18",NOMBRE:"Heung-min Son"},
{NUM:"KOR19",NOMBRE:"Hee-chan Hwang"},
{NUM:"KOR20",NOMBRE:"Hyeon-Gyu Oh"},
{NUM:"KSA1",NOMBRE:"Foto del escudo"},
{NUM:"KSA2",NOMBRE:"Nawaf Alaqidi"},
{NUM:"KSA3",NOMBRE:"Abdulrahman Al-Sanbi"},
{NUM:"KSA4",NOMBRE:"Saud Abdulhamid"},
{NUM:"KSA5",NOMBRE:"Nawaf Bouwashl"},
{NUM:"KSA6",NOMBRE:"Jihad Thakri"},
{NUM:"KSA7",NOMBRE:"Moteb Al-Harbi"},
{NUM:"KSA8",NOMBRE:"Hassan Altambakti"},
{NUM:"KSA9",NOMBRE:"Musab Aljuwayr"},
{NUM:"KSA10",NOMBRE:"Ziyad Aljohani"},
{NUM:"KSA11",NOMBRE:"Abdullah Alkhaibari"},
{NUM:"KSA12",NOMBRE:"Nasser Aldawsari"},
{NUM:"KSA13",NOMBRE:"Foto del equipo"},
{NUM:"KSA14",NOMBRE:"Saleh Abu Alshamat"},
{NUM:"KSA15",NOMBRE:"Marwan Alsahafi"},
{NUM:"KSA16",NOMBRE:"Salem Aldawsari"},
{NUM:"KSA17",NOMBRE:"Abdulrahman Al-Aboud"},
{NUM:"KSA18",NOMBRE:"Feras Akbrikan"},
{NUM:"KSA19",NOMBRE:"Saleh Alshehri"},
{NUM:"KSA20",NOMBRE:"Abdullah Al-Hamdan"},
{NUM:"36951",NOMBRE:"Foto del escudo"},
{NUM:"37316",NOMBRE:"Yassine Bounou"},
{NUM:"37681",NOMBRE:"Munir El Kajoui"},
{NUM:"38047",NOMBRE:"Achraf Hakimi"},
{NUM:"38412",NOMBRE:"Noussair Mazraoui"},
{NUM:"38777",NOMBRE:"Nayef Aguerd"},
{NUM:"39142",NOMBRE:"Roman Saiss"},
{NUM:"39508",NOMBRE:"Jawad El Yamio"},
{NUM:"39873",NOMBRE:"Adam Masina"},
{NUM:"40238",NOMBRE:"Sofyan Amrabat"},
{NUM:"40603",NOMBRE:"Azzedine Ounahi"},
{NUM:"40969",NOMBRE:"Eliesse Ben Seghir"},
{NUM:"41334",NOMBRE:"Foto del equipo"},
{NUM:"41699",NOMBRE:"Bilal El Khannouss"},
{NUM:"42064",NOMBRE:"Ismael Saibari"},
{NUM:"42430",NOMBRE:"Youssef En-Nesyri"},
{NUM:"42795",NOMBRE:"Abde Ezzalzouli"},
{NUM:"43160",NOMBRE:"Soufiane Rahimi"},
{NUM:"43525",NOMBRE:"Brahim Diaz"},
{NUM:"43891",NOMBRE:"Ayoub El Kaabi"},
{NUM:"MEX1",NOMBRE:"Foto del escudo"},
{NUM:"MEX2",NOMBRE:"Luis Malagón"},
{NUM:"MEX3",NOMBRE:"Johan Vasquez"},
{NUM:"MEX4",NOMBRE:"Jorge Sánchez"},
{NUM:"MEX5",NOMBRE:"Cesar Montes"},
{NUM:"MEX6",NOMBRE:"Jesus Gallardo"},
{NUM:"MEX7",NOMBRE:"Israel Reyes"},
{NUM:"MEX8",NOMBRE:"Diego Lainez"},
{NUM:"MEX9",NOMBRE:"Carlos Rodriguez"},
{NUM:"MEX10",NOMBRE:"Edson Alvarez"},
{NUM:"MEX11",NOMBRE:"Orbelin Pineda"},
{NUM:"MEX12",NOMBRE:"Marcel Ruiz"},
{NUM:"MEX13",NOMBRE:"Foto del equipo"},
{NUM:"MEX14",NOMBRE:"Érick Sánchez"},
{NUM:"MEX15",NOMBRE:"Hirving Lozano"},
{NUM:"MEX16",NOMBRE:"Santiago Giménez"},
{NUM:"MEX17",NOMBRE:"Raúl Jiménez"},
{NUM:"MEX18",NOMBRE:"Alexis Vega"},
{NUM:"MEX19",NOMBRE:"Roberto Alvarado"},
{NUM:"MEX20",NOMBRE:"Cesar Huerta"},
{NUM:"NED1",NOMBRE:"Foto del escudo"},
{NUM:"NED2",NOMBRE:"Bart Verbruggen"},
{NUM:"NED3",NOMBRE:"Virgil van Dijk"},
{NUM:"NED4",NOMBRE:"Micky van de Ven"},
{NUM:"NED5",NOMBRE:"Jurrien Timber"},
{NUM:"NED6",NOMBRE:"Denzel Dumfries"},
{NUM:"NED7",NOMBRE:"Nathan Aké"},
{NUM:"NED8",NOMBRE:"Jeremie Frimpong"},
{NUM:"NED9",NOMBRE:"Jan Paul van Hecke"},
{NUM:"NED10",NOMBRE:"Tijjani Reijnders"},
{NUM:"NED11",NOMBRE:"Ryan Gravenberch"},
{NUM:"NED12",NOMBRE:"Teun Koopmeiners"},
{NUM:"NED13",NOMBRE:"Foto del equipo"},
{NUM:"NED14",NOMBRE:"Frenkie de Jong"},
{NUM:"NED15",NOMBRE:"Xavi Simons"},
{NUM:"NED16",NOMBRE:"Justin Kluivert"},
{NUM:"NED17",NOMBRE:"Memphis Depay"},
{NUM:"NED18",NOMBRE:"Donyell Malen"},
{NUM:"NED19",NOMBRE:"Wout Weghorst"},
{NUM:"NED20",NOMBRE:"Cody Gakpo"},
{NUM:"NOR1",NOMBRE:"Foto del escudo"},
{NUM:"NOR2",NOMBRE:"Orjan Nyland"},
{NUM:"NOR3",NOMBRE:"Julian Ryerson"},
{NUM:"NOR4",NOMBRE:"Leo Ostigård"},
{NUM:"NOR5",NOMBRE:"Kristoffer Vassbakk Ajer"},
{NUM:"NOR6",NOMBRE:"Marcus Holmgren Pedersen"},
{NUM:"NOR7",NOMBRE:"David Møller Wolfe"},
{NUM:"NOR8",NOMBRE:"Torbjørn Heggem"},
{NUM:"NOR9",NOMBRE:"Morten Thorsby"},
{NUM:"NOR10",NOMBRE:"Martin Ødegaard"},
{NUM:"NOR11",NOMBRE:"Sander Berge"},
{NUM:"NOR12",NOMBRE:"Andreas Schjelderup"},
{NUM:"NOR13",NOMBRE:"Foto del equipo"},
{NUM:"NOR14",NOMBRE:"Patrick Berg"},
{NUM:"NOR15",NOMBRE:"Erling Haaland"},
{NUM:"NOR16",NOMBRE:"Alexander Sørloth"},
{NUM:"NOR17",NOMBRE:"Aron Dønnum"},
{NUM:"NOR18",NOMBRE:"Jorgen Strand Larsen"},
{NUM:"NOR19",NOMBRE:"Antonio Nusa"},
{NUM:"NOR20",NOMBRE:"Oscar Bobb"},
{NUM:"NZL1",NOMBRE:"Foto del escudo"},
{NUM:"NZL2",NOMBRE:"Max Crocombe Payne"},
{NUM:"NZL3",NOMBRE:"Alex Paulsen"},
{NUM:"NZL4",NOMBRE:"Michael Boxall"},
{NUM:"NZL5",NOMBRE:"Liberato Cacace"},
{NUM:"NZL6",NOMBRE:"Tim Payne"},
{NUM:"NZL7",NOMBRE:"Tyler Bindon"},
{NUM:"NZL8",NOMBRE:"Francis de Vries"},
{NUM:"NZL9",NOMBRE:"Finn Surman"},
{NUM:"NZL10",NOMBRE:"Joe Bell"},
{NUM:"NZL11",NOMBRE:"Sarpreet Singh"},
{NUM:"NZL12",NOMBRE:"Ryan Thomas"},
{NUM:"NZL13",NOMBRE:"Foto del equipo"},
{NUM:"NZL14",NOMBRE:"Matthew Garbett"},
{NUM:"NZL15",NOMBRE:"Marko Stamenić"},
{NUM:"NZL16",NOMBRE:"Ben Old"},
{NUM:"NZL17",NOMBRE:"Chris Wood"},
{NUM:"NZL18",NOMBRE:"Elijah Just"},
{NUM:"NZL19",NOMBRE:"Callum McCowatt"},
{NUM:"NZL20",NOMBRE:"Kosta Barbarouses"},
{NUM:"PAN1",NOMBRE:"Foto del escudo"},
{NUM:"PAN2",NOMBRE:"Orlando Mosquera"},
{NUM:"PAN3",NOMBRE:"Luis Mejia"},
{NUM:"PAN4",NOMBRE:"Fidel Escobar"},
{NUM:"PAN5",NOMBRE:"Andres Andrade"},
{NUM:"PAN6",NOMBRE:"Michael Amir Murillo"},
{NUM:"PAN7",NOMBRE:"Eric Davis"},
{NUM:"PAN8",NOMBRE:"Jose Cordoba"},
{NUM:"PAN9",NOMBRE:"Cesar Blackman"},
{NUM:"PAN10",NOMBRE:"Cristian Martinez"},
{NUM:"PAN11",NOMBRE:"Aníbal Godoy"},
{NUM:"PAN12",NOMBRE:"Adalberto Carrasquilla"},
{NUM:"PAN13",NOMBRE:"Foto del equipo"},
{NUM:"PAN14",NOMBRE:"Édgar Bárcenas"},
{NUM:"PAN15",NOMBRE:"Carlos Harvey"},
{NUM:"PAN16",NOMBRE:"Ismael Díaz"},
{NUM:"PAN17",NOMBRE:"Jose Fajardo"},
{NUM:"PAN18",NOMBRE:"Cecilio Waterman"},
{NUM:"PAN19",NOMBRE:"Jose Luiz Rodriguez"},
{NUM:"PAN20",NOMBRE:"Alberto Quintero"},
{NUM:"PAR1",NOMBRE:"Foto del escudo"},
{NUM:"PAR2",NOMBRE:"Roberto Fernandez"},
{NUM:"PAR3",NOMBRE:"Orlando Gill"},
{NUM:"PAR4",NOMBRE:"Gustavo Gomez"},
{NUM:"PAR5",NOMBRE:"Fabián Balbuena"},
{NUM:"PAR6",NOMBRE:"Juan José Cáceres"},
{NUM:"PAR7",NOMBRE:"Omar Alderete"},
{NUM:"PAR8",NOMBRE:"Junior Alonso"},
{NUM:"PAR9",NOMBRE:"Mathías Villasanti"},
{NUM:"PAR10",NOMBRE:"Diego Gomez"},
{NUM:"PAR11",NOMBRE:"Damián Bobadilla"},
{NUM:"PAR12",NOMBRE:"Andres Cubas"},
{NUM:"PAR13",NOMBRE:"Foto del equipo"},
{NUM:"PAR14",NOMBRE:"Matias Galarza Fonda"},
{NUM:"PAR15",NOMBRE:"Julio Enciso"},
{NUM:"PAR16",NOMBRE:"Alejandro Romero Gamarra"},
{NUM:"PAR17",NOMBRE:"Miguel Almirón"},
{NUM:"PAR18",NOMBRE:"Ramon Sosa"},
{NUM:"PAR19",NOMBRE:"Angel Romero"},
{NUM:"PAR20",NOMBRE:"Antonio Sanabria"},
{NUM:"POR1",NOMBRE:"Foto del escudo"},
{NUM:"POR2",NOMBRE:"Diogo Costa"},
{NUM:"POR3",NOMBRE:"Jose Sa"},
{NUM:"POR4",NOMBRE:"Ruben Dias"},
{NUM:"POR5",NOMBRE:"João Cancelo"},
{NUM:"POR6",NOMBRE:"Diogo Dalot"},
{NUM:"POR7",NOMBRE:"Nuno Mendes"},
{NUM:"POR8",NOMBRE:"Gonçalo Inácio"},
{NUM:"POR9",NOMBRE:"Bernardo Silva"},
{NUM:"POR10",NOMBRE:"Bruno Fernandes"},
{NUM:"POR11",NOMBRE:"Ruben Neves"},
{NUM:"POR12",NOMBRE:"Vitinha"},
{NUM:"POR13",NOMBRE:"Foto del equipo"},
{NUM:"POR14",NOMBRE:"João Neves"},
{NUM:"POR15",NOMBRE:"Cristiano Ronaldo"},
{NUM:"POR16",NOMBRE:"Francisco Trincao"},
{NUM:"POR17",NOMBRE:"João Felix"},
{NUM:"POR18",NOMBRE:"Gonçalo Ramos"},
{NUM:"POR19",NOMBRE:"Pedro Neto"},
{NUM:"POR20",NOMBRE:"Rafael Leão"},
{NUM:"QAT1",NOMBRE:"Foto del escudo"},
{NUM:"QAT2",NOMBRE:"Meshaal Barsham"},
{NUM:"QAT3",NOMBRE:"Sultan Albrake"},
{NUM:"QAT4",NOMBRE:"Lucas Mendes"},
{NUM:"QAT5",NOMBRE:"Homam Ahmed"},
{NUM:"QAT6",NOMBRE:"Boualem Khoukhi"},
{NUM:"QAT7",NOMBRE:"Pedro Miguel"},
{NUM:"QAT8",NOMBRE:"Tarek Salman"},
{NUM:"QAT9",NOMBRE:"Mohamed Al-Mannai"},
{NUM:"QAT10",NOMBRE:"Karim Boudiaf"},
{NUM:"QAT11",NOMBRE:"Assim Madibo"},
{NUM:"QAT12",NOMBRE:"Ahmed Fatehi"},
{NUM:"QAT13",NOMBRE:"Foto del equipo"},
{NUM:"QAT14",NOMBRE:"Mohammed Waad"},
{NUM:"QAT15",NOMBRE:"Abdulaziz Hatem"},
{NUM:"QAT16",NOMBRE:"Hassan Al-Haydos"},
{NUM:"QAT17",NOMBRE:"Edmilson Junior"},
{NUM:"QAT18",NOMBRE:"Akram Hassan Afif"},
{NUM:"QAT19",NOMBRE:"Ahmed Al Ganehi"},
{NUM:"QAT20",NOMBRE:"Almoez Ali"},
{NUM:"RSA1",NOMBRE:"Foto del escudo"},
{NUM:"RSA2",NOMBRE:"Ronwen Williams"},
{NUM:"RSA3",NOMBRE:"Sipho Chaine"},
{NUM:"RSA4",NOMBRE:"Aubrey Modiba"},
{NUM:"RSA5",NOMBRE:"Samukele Kabini"},
{NUM:"RSA6",NOMBRE:"Mbekezeli Mbokazi"},
{NUM:"RSA7",NOMBRE:"Khulumani Ndamane"},
{NUM:"RSA8",NOMBRE:"Siyabonga Ngezana"},
{NUM:"RSA9",NOMBRE:"Khuliso Mudau"},
{NUM:"RSA10",NOMBRE:"Nkosinathi Sibisi"},
{NUM:"RSA11",NOMBRE:"Teboho Mokoena"},
{NUM:"RSA12",NOMBRE:"Thalente Mbatha"},
{NUM:"RSA13",NOMBRE:"Foto del equipo"},
{NUM:"RSA14",NOMBRE:"Bathasi Aubaas"},
{NUM:"RSA15",NOMBRE:"Yaya Sithole"},
{NUM:"RSA16",NOMBRE:"Sipho Mbule"},
{NUM:"RSA17",NOMBRE:"Lyle Foster"},
{NUM:"RSA18",NOMBRE:"Iqraam Rayners"},
{NUM:"RSA19",NOMBRE:"Mohau Nkota"},
{NUM:"RSA20",NOMBRE:"Oswin Appollis"},
{NUM:"SCO1",NOMBRE:"Foto del escudo"},
{NUM:"SCO2",NOMBRE:"Angus Gunn"},
{NUM:"SCO3",NOMBRE:"Jack Hendry"},
{NUM:"SCO4",NOMBRE:"Kieran Tierney"},
{NUM:"SCO5",NOMBRE:"Aaron Hickey"},
{NUM:"SCO6",NOMBRE:"Andrew Robertson"},
{NUM:"SCO7",NOMBRE:"Scott McKenna"},
{NUM:"SCO8",NOMBRE:"John Souttar"},
{NUM:"SCO9",NOMBRE:"Anthony Ralston"},
{NUM:"SCO10",NOMBRE:"Grant Hanley"},
{NUM:"SCO11",NOMBRE:"Scott McTominay"},
{NUM:"SCO12",NOMBRE:"Billy Gilmour"},
{NUM:"SCO13",NOMBRE:"Foto del equipo"},
{NUM:"SCO14",NOMBRE:"Lewis Ferguson"},
{NUM:"SCO15",NOMBRE:"Ryan Christie"},
{NUM:"SCO16",NOMBRE:"Kenny McLean"},
{NUM:"SCO17",NOMBRE:"John McGinn"},
{NUM:"SCO18",NOMBRE:"Lyndon Dykes"},
{NUM:"SCO19",NOMBRE:"Che Adams"},
{NUM:"SCO20",NOMBRE:"Ben Gannon-Doak"},
{NUM:"SEN1",NOMBRE:"Foto del escudo"},
{NUM:"SEN2",NOMBRE:"Edouard Mendy"},
{NUM:"SEN3",NOMBRE:"Yehvann Diouf"},
{NUM:"SEN4",NOMBRE:"Moussa Niakhaté"},
{NUM:"SEN5",NOMBRE:"Abdoulaye Seck"},
{NUM:"SEN6",NOMBRE:"Ismail Jakobs"},
{NUM:"SEN7",NOMBRE:"El Hadji Malick Diouf"},
{NUM:"SEN8",NOMBRE:"Kalidou Koulibaly"},
{NUM:"SEN9",NOMBRE:"Idrissa Gana Gueye"},
{NUM:"SEN10",NOMBRE:"Pape Matar Sarr"},
{NUM:"SEN11",NOMBRE:"Pape Gueye"},
{NUM:"SEN12",NOMBRE:"Habib Diarra"},
{NUM:"SEN13",NOMBRE:"Foto del equipo"},
{NUM:"SEN14",NOMBRE:"Lamine Camara"},
{NUM:"SEN15",NOMBRE:"Sadio Mane"},
{NUM:"SEN16",NOMBRE:"Ismaïla Sarr"},
{NUM:"SEN17",NOMBRE:"Boulaye Dia"},
{NUM:"SEN18",NOMBRE:"Iliman Ndiaye"},
{NUM:"SEN19",NOMBRE:"Nicolas Jackson"},
{NUM:"SEN20",NOMBRE:"Krepin Diatta"},
{NUM:"SUI1",NOMBRE:"Foto del escudo"},
{NUM:"SUI2",NOMBRE:"Gregor Kobel"},
{NUM:"SUI3",NOMBRE:"Yvon Mvogo"},
{NUM:"SUI4",NOMBRE:"Manuel Akanji"},
{NUM:"SUI5",NOMBRE:"Ricardo Rodriguez"},
{NUM:"SUI6",NOMBRE:"Nico Elvedi"},
{NUM:"SUI7",NOMBRE:"Aurèle Amenda"},
{NUM:"SUI8",NOMBRE:"Silvan Widmer"},
{NUM:"SUI9",NOMBRE:"Granit Xhaka"},
{NUM:"SUI10",NOMBRE:"Denis Zakaria"},
{NUM:"SUI11",NOMBRE:"Remo Freuler"},
{NUM:"SUI12",NOMBRE:"Fabian Rieder"},
{NUM:"SUI13",NOMBRE:"Foto del equipo"},
{NUM:"SUI14",NOMBRE:"Ardon Jashari"},
{NUM:"SUI15",NOMBRE:"Johan Manzambi"},
{NUM:"SUI16",NOMBRE:"Michel Aebischer"},
{NUM:"SUI17",NOMBRE:"Breel Embolo"},
{NUM:"SUI18",NOMBRE:"Ruben Vargas"},
{NUM:"SUI19",NOMBRE:"Dan Ndoye"},
{NUM:"SUI20",NOMBRE:"Zeki Amdouni"},
{NUM:"SWE1",NOMBRE:"Foto del escudo"},
{NUM:"SWE2",NOMBRE:"Victor Johansson"},
{NUM:"SWE3",NOMBRE:"Isak Hien"},
{NUM:"SWE4",NOMBRE:"Gabriel Gudmundsson"},
{NUM:"SWE5",NOMBRE:"Emil Holm"},
{NUM:"SWE6",NOMBRE:"Victor Nilsson Lindelöf"},
{NUM:"SWE7",NOMBRE:"Gustaf Lagerbielke"},
{NUM:"SWE8",NOMBRE:"Lucas Bergvall"},
{NUM:"SWE9",NOMBRE:"Hugo Larsson"},
{NUM:"SWE10",NOMBRE:"Jesper Karlström"},
{NUM:"SWE11",NOMBRE:"Yasin Ayari"},
{NUM:"SWE12",NOMBRE:"Mattias Svanberg"},
{NUM:"SWE13",NOMBRE:"Foto del equipo"},
{NUM:"SWE14",NOMBRE:"Daniel Svensson"},
{NUM:"SWE15",NOMBRE:"Ken Sema"},
{NUM:"SWE16",NOMBRE:"Roony Bardghji"},
{NUM:"SWE17",NOMBRE:"Dejan Kulusevski"},
{NUM:"SWE18",NOMBRE:"Anthony Elanga"},
{NUM:"SWE19",NOMBRE:"Alexander Isak"},
{NUM:"SWE20",NOMBRE:"Viktor Gyökeres"},
{NUM:"TUN1",NOMBRE:"Foto del escudo"},
{NUM:"TUN2",NOMBRE:"Bechir Ben Said"},
{NUM:"TUN3",NOMBRE:"Aymen Dahmen"},
{NUM:"TUN4",NOMBRE:"Yan Valery"},
{NUM:"TUN5",NOMBRE:"Montassar Talbi"},
{NUM:"TUN6",NOMBRE:"Yassine Meriah"},
{NUM:"TUN7",NOMBRE:"Ali Abdi"},
{NUM:"TUN8",NOMBRE:"Dylan Bronn"},
{NUM:"TUN9",NOMBRE:"Ellyes Skhiri"},
{NUM:"TUN10",NOMBRE:"Aissa Laidouni"},
{NUM:"TUN11",NOMBRE:"Ferjani Sassi"},
{NUM:"TUN12",NOMBRE:"Mohamed Ali Ben Romdhane"},
{NUM:"TUN13",NOMBRE:"Foto del equipo"},
{NUM:"TUN14",NOMBRE:"Hannibal Mejbri"},
{NUM:"TUN15",NOMBRE:"Elias Achouri"},
{NUM:"TUN16",NOMBRE:"Elias Saad"},
{NUM:"TUN17",NOMBRE:"Hazem Mastouri"},
{NUM:"TUN18",NOMBRE:"Ismael Gharbi"},
{NUM:"TUN19",NOMBRE:"Sayfallah Ltaief"},
{NUM:"TUN20",NOMBRE:"Naim Sliti"},
{NUM:"TUR1",NOMBRE:"Foto del escudo"},
{NUM:"TUR2",NOMBRE:"Ugurcan Cakir"},
{NUM:"TUR3",NOMBRE:"Mert Muldur"},
{NUM:"TUR4",NOMBRE:"Zeki Celik"},
{NUM:"TUR5",NOMBRE:"Abdulkerim Bardakci"},
{NUM:"TUR6",NOMBRE:"Caglar Soyuncu"},
{NUM:"TUR7",NOMBRE:"Merih Demiral"},
{NUM:"TUR8",NOMBRE:"Ferdi Kadioglu"},
{NUM:"TUR9",NOMBRE:"Kaan Ayhan"},
{NUM:"TUR10",NOMBRE:"Ismail Yuksek"},
{NUM:"TUR11",NOMBRE:"Hakan Calhanoglu"},
{NUM:"TUR12",NOMBRE:"Orkun Kokcu"},
{NUM:"TUR13",NOMBRE:"Foto del equipo"},
{NUM:"TUR14",NOMBRE:"Arda Guler"},
{NUM:"TUR15",NOMBRE:"Irfan Can Kahveci"},
{NUM:"TUR16",NOMBRE:"Yunus Akgun"},
{NUM:"TUR17",NOMBRE:"Can Uzun"},
{NUM:"TUR18",NOMBRE:"Baris Alper Yilmaz"},
{NUM:"TUR19",NOMBRE:"Kerem Akturkoglu"},
{NUM:"TUR20",NOMBRE:"Kenan Yildiz"},
{NUM:"URU1",NOMBRE:"Foto del escudo"},
{NUM:"URU2",NOMBRE:"Sergio Rochet"},
{NUM:"URU3",NOMBRE:"Santiago Mele"},
{NUM:"URU4",NOMBRE:"Ronald Araujo"},
{NUM:"URU5",NOMBRE:"José María Giménez"},
{NUM:"URU6",NOMBRE:"Sebastian Caceres"},
{NUM:"URU7",NOMBRE:"Mathias Olivera"},
{NUM:"URU8",NOMBRE:"Guillermo Varela"},
{NUM:"URU9",NOMBRE:"Nahitan Nandez"},
{NUM:"URU10",NOMBRE:"Federico Valverde"},
{NUM:"URU11",NOMBRE:"Giorgian De Arrascaeta"},
{NUM:"URU12",NOMBRE:"Rodrigo Bentancur"},
{NUM:"URU13",NOMBRE:"Foto del equipo"},
{NUM:"URU14",NOMBRE:"Manuel Ugarte"},
{NUM:"URU15",NOMBRE:"Nicolás de la Cruz"},
{NUM:"URU16",NOMBRE:"Maxi Araujo"},
{NUM:"URU17",NOMBRE:"Darwin Núñez"},
{NUM:"URU18",NOMBRE:"Federico Viñas"},
{NUM:"URU19",NOMBRE:"Rodrigo Aguirre"},
{NUM:"URU20",NOMBRE:"Facundo Pellistri"},
{NUM:"USA1",NOMBRE:"Foto del escudo"},
{NUM:"USA2",NOMBRE:"Math Freese"},
{NUM:"USA3",NOMBRE:"Chris Richards"},
{NUM:"USA4",NOMBRE:"Tim Ream"},
{NUM:"USA5",NOMBRE:"Mark McKenzie"},
{NUM:"USA6",NOMBRE:"Alex Freeman"},
{NUM:"USA7",NOMBRE:"Antonee Robinson"},
{NUM:"USA8",NOMBRE:"Tyler Adams"},
{NUM:"USA9",NOMBRE:"Tanner Tessmann"},
{NUM:"USA10",NOMBRE:"Weston McKenny"},
{NUM:"USA11",NOMBRE:"Christian Roldan"},
{NUM:"USA12",NOMBRE:"Timothy Weah"},
{NUM:"USA13",NOMBRE:"Foto del equipo"},
{NUM:"USA14",NOMBRE:"Diego Luna"},
{NUM:"USA15",NOMBRE:"Malik Tillman"},
{NUM:"USA16",NOMBRE:"Christian Pulisic"},
{NUM:"USA17",NOMBRE:"Brenden Aaronson"},
{NUM:"USA18",NOMBRE:"Ricardo Pepi"},
{NUM:"USA19",NOMBRE:"Haji Wright"},
{NUM:"USA20",NOMBRE:"Folarin Balogun"},
{NUM:"UZB1",NOMBRE:"Foto del escudo"},
{NUM:"UZB2",NOMBRE:"Utkir Yusupov"},
{NUM:"UZB3",NOMBRE:"Farrukh Savfiev"},
{NUM:"UZB4",NOMBRE:"Sherzod Nasrullaev"},
{NUM:"UZB5",NOMBRE:"Umar Eshmurodov"},
{NUM:"UZB6",NOMBRE:"Husniddin Aliqulov"},
{NUM:"UZB7",NOMBRE:"Rustamjon Ashurmatov"},
{NUM:"UZB8",NOMBRE:"Khojiakbar Alijonov"},
{NUM:"UZB9",NOMBRE:"Abdukodir Khusanov"},
{NUM:"UZB10",NOMBRE:"Odiljon Hamrobekov"},
{NUM:"UZB11",NOMBRE:"Otabek Shukurov"},
{NUM:"UZB12",NOMBRE:"Jamshid Iskanderov"},
{NUM:"UZB13",NOMBRE:"Foto del equipo"},
{NUM:"UZB14",NOMBRE:"Azizbek Turgunboev"},
{NUM:"UZB15",NOMBRE:"Khojimat Erkinov"},
{NUM:"UZB16",NOMBRE:"Eldor Shomurodov"},
{NUM:"UZB17",NOMBRE:"Oston Urunov"},
{NUM:"UZB18",NOMBRE:"Jaloliddin Masharipov"},
{NUM:"UZB19",NOMBRE:"Igor Sergeev"},
{NUM:"UZB20",NOMBRE:"Abbosbek Fayzullaev"},
{NUM:"FWC1",NOMBRE:"Official Emblem"},
{NUM:"FWC2",NOMBRE:"Official Emblem"},
{NUM:"FWC3",NOMBRE:"Official Mascots"},
{NUM:"FWC4",NOMBRE:"Official Slogan"},
{NUM:"FWC5",NOMBRE:"Official Ball"},
{NUM:"FWC6",NOMBRE:"Canada - Host Countries & Cities"},
{NUM:"FWC7",NOMBRE:"Mexico - Host Countries & Cities"},
{NUM:"FWC8",NOMBRE:"USA - Host Countries & Cities"},
{NUM:"FWC9",NOMBRE:"Italy 1934 - World Cup History"},
{NUM:"FWC10",NOMBRE:"Uruguay 1950 - World Cup History"},
{NUM:"FWC11",NOMBRE:"West Germany 1954 - World Cup History"},
{NUM:"FWC12",NOMBRE:"Brazil 1962 - World Cup History"},
{NUM:"FWC13",NOMBRE:"West Germany 1974 - World Cup History"},
{NUM:"FWC14",NOMBRE:"Argentina 1986 - World Cup History"},
{NUM:"FWC15",NOMBRE:"Brazil 1994 - World Cup History"},
{NUM:"FWC16",NOMBRE:"Brazil 2002 - World Cup History"},
{NUM:"FWC17",NOMBRE:"Italy 2006 - World Cup History"},
{NUM:"FWC18",NOMBRE:"Germany 2014 - World Cup History"},
{NUM:"FWC19",NOMBRE:"Argentina 2022 - World Cup History"}
]

for (const figu of figuritas) {
    
    for (const n of nombres){
        if (n.NUM===figu.NUM){
            figu.NOMBRE=n.NOMBRE
            console.log(figu.NOMBRE)
        }
    }
    


    await figu.save();
}

console.log(` migrado`);


await mongoose.disconnect();